### ISSUE TITLE
Regression train crashes

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#88]
When an algorithm is chosen in the regression_train_ gui, the program crashes entirely!! **This needs to be fixed ASAP**. Here is the traceback:

Traceback (most recent call last):
  File "C:\Users\rbanderson\Documents\Projects\LIBS PDART\PySAT_Point_Spectra_GUI\point_spectra_gui\ui_modules\regression_train_.py", line 45, in <lambda>
    lambda: self.make_regression_widget(self.regression_choosealg.currentText()))  #
  File "C:\Users\rbanderson\Documents\Projects\LIBS PDART\PySAT_Point_Spectra_GUI\point_spectra_gui\ui_modules\regression_train_.py", line 343, in make_regression_widget
    self.qtickle.isGuiChanged(self.pls, self.get_regression_parameters)
TypeError: isGuiChanged() takes 2 positional arguments but 3 were given
PLS
<class 'TypeError'> isGuiChanged() takes 2 positional arguments but 3 were given <traceback object at 0x000000000AA79BC8>

**Comment by tisaconundrum2** [comment]
Taking a look at it now
I will push a new version to you as soon as it's fixed

**Comment by tisaconundrum2** [comment]
PR https://github.com/ryanbanderson/PySAT_Point_Spectra_GUI/pull/9 fixes this problem
