### ISSUE TITLE
Add ability to pickle/restore trained models

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PySAT_Point_Spectra_GUI#98]
This will ideally include a way to inform the user of what preprocessing steps were performed prior to training the model.

**Comment by tisaconundrum2** [comment]
During Testing
---

When trying to predict on a particular set of data, we get an error because the given dataset doesn't actually have a trained column. @ryanbanderson Please advise. 

```
Traceback (most recent call last):
  File "C:\Users\tisaconundrum\Desktop\GitHub\PySAT_Point_Spectra_GUI\point_spectra_gui\core\MainWindow.py", line 640, in _exceptionLogger
    function()
  File "C:\Users\tisaconundrum\Desktop\GitHub\PySAT_Point_Spectra_GUI\point_spectra_gui\core\MainWindow.py", line 615, in runModules
    self.widgetList[modules].run()
  File "C:\Users\tisaconundrum\Desktop\GitHub\PySAT_Point_Spectra_GUI\point_spectra_gui\core\RegressionPredict.py", line 44, in run
    data_tmp = self.data[datakey].df[self.model_xvars[modelkey]]
KeyError: 'PLS - SiO2 - (0.0, 100.0) (nc=2)'
```

**Comment by tisaconundrum2** [comment]
Fixed

**Comment by ryanbanderson** [comment]
I added this functionality with #236
